// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmnpkvhzhyfhdhsgbmkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtbnBrdmh6aHlmaGRoc2dibWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NDQ4MDQsImV4cCI6MjA1NDUyMDgwNH0.tRH9y5Qg00LZLa2uhmiYhokk3UKEKBgagKcUi0PnAnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);